### ISSUE TITLE
Text values are hardcoded. No ability to add translations.

### ISSUE THREAD

**Issue by filipfonal** [stephenjude/filament-blog#10]
Please add the ability for localization.

**Comment by stephenjude** [comment]
@filipfonal  Can you make a PR for that?

**Comment by filipfonal** [comment]
Yes, created https://github.com/stephenjude/filament-blog/pull/11

**Comment by stephenjude** [comment]
Okay, I will check it out

**Comment by stephenjude** [comment]
I have tagged a release — https://github.com/stephenjude/filament-blog/releases/tag/0.1.6

Thank you.
