### ISSUE TITLE
add option to remove author 

### ISSUE THREAD

**Issue by ariaieboy** [stephenjude/filament-blog#15]
hello
In many projects, we have a User model that can be used as the author in the blog section. So we can use the User as the author for the posts.

Another option could be using the currently logged-in user as the author.

If you want I can make a PR for this in my next free time .

**Comment by stephenjude** [comment]
That makes sense, let me know when you make a PR.

**Comment by ariaieboy** [comment]
> That makes sense, let me know when you make a PR.

since I need this feature in one of my projects I am trying to create some PRs today
