### ISSUE TITLE
Problem to upload image to S3

### ISSUE THREAD

**Issue by JordanchoEftimov** [stephenjude/filament-blog#25]
So i've recently installed this plugin and i absolutely love it, but when i try to configure it to store my images to S3 AWS its not working. So when i upload the image firstly the preview it is stored in the bucket, but then when i create the author/post/etc it transfers the images to the server and deletes them from the bucket. 

Any help would be appreciated. My default storage is S3, i've set up FILAMENT_FILESYSTEM_DRIVER=s3 as well and my credentials are okay.

**Comment by stephenjude** [comment]
Hi @JordanchoEftimov 

I have used Filament with Digital Ocean Space using an s3 compatible driver. It works fine by setting both the filament filesystem and the laravel filesystem driver to use the s3 and it works without any other configuration.
