### ISSUE TITLE
Add fillable property [blog_author_id, blog_category_id]

### ISSUE THREAD

**Issue by sophy** [stephenjude/filament-blog#26]
### Feature description

Please add both fields `blog_author_id` and `blog_category_id` into fillable of `Post` model. Because I got this error `Illuminate\Database\Eloquent\MassAssignmentException`

`Add fillable property [blog_author_id, blog_category_id] to allow mass assignment on [Stephenjude\FilamentBlog\Models\Post].`

**Comment by stephenjude** [comment]
I will suggest you unguard these models from the `boot` method of the `AppServiceProvider` class. Like this:

```php
Post::unguard();

```

**Comment by sophy** [comment]
Thank you Stephen
