### ISSUE TITLE
Typo in method name (sortable, not sotable)

### ISSUE THREAD

**Issue by Zeriz** [stephenjude/filament-blog#32]
### Filament Blog Version

0.1.6

### Filament Version

2.0.0

### Laravel Version

10.0.0

### Livewire Version

2.0.0

### PHP Version

8.2

### Problem description

PostResource.php has a typo on line 139, where it calls for sotable(), but should've called for sortable().

### Expected behavior

I expected the Posts page to view it's content, but the typo prevented it and displayed an error instead.

### Steps to reproduce

Install the current  version of the package, go to Posts page.

### Reproduction repository

https://github.com/stephenjude/filament-blog/blob/main/src/Resources/PostResource.php#L139

**Comment by stephenjude** [comment]
Thanks for catching this @Zeriz 

I have fixed and tagged a release. version 1.1.1
