### ISSUE TITLE
There is no instruction on how to add new languages in the laravel configuration

### ISSUE THREAD

**Issue by viterzbayraku** [stephenjude/filament-blog#45]
### Feature description

I want to add non english language on lang folder for main laravel directory. But don't see instruction for this. Please add a tutorial to the plugin documentation. Thank you.

**Comment by DmitriyDalee** [comment]
Hei! You can follow https://laravel.com/docs/10.x/localization#overriding-package-language-files
But some of menu items has no effect for this setup - is needed some edits

**Comment by viterzbayraku** [comment]
> Hei! You can follow https://laravel.com/docs/10.x/localization#overriding-package-language-files
> But some of menu items has no effect for this setup - is needed some edits

I am asking the plugin developer about this. Because is not correct to modify the plugin files in the vendor folder.

**Comment by DmitriyDalee** [comment]
You no need to modify vendor.
You should add your translation to resources/lang/vendor/filament-blog/<YOUR_SHORT_LANGUAGE>/filament-blog.php

I'm also want to add some translation via Pull Request

**Comment by viterzbayraku** [comment]
> You no need to modify vendor. You should add your translation to resources/lang/vendor/filament-blog/<YOUR_SHORT_LANGUAGE>/filament-blog.php
> 
> I'm also want to add some translation via Pull Request

You were do not understand me. I'm talking about implementation of multilanguage content in blog plugin (Spatie Translatable) instead of the interface translations.

**Comment by stephenjude** [comment]
Thank you for providing a reference @DmitriyDalee 

@viterzbayraku you don't need to modify vendor. Follow the guide provided by @DmitriyDalee and I will be happy to merge your PR.

**Comment by viterzbayraku** [comment]
> Thank you for providing a reference @DmitriyDalee 
> 
> @viterzbayraku you don't need to modify vendor. Follow the guide provided by @DmitriyDalee and I will be happy to merge your PR.
> 

Sorry. I have an additional question about Spatie Translatable implementation.
