### ISSUE TITLE
Adding this plugin to filamentphp.com

### ISSUE THREAD

**Issue by danharrin** [stephenjude/filament-blog#5]
Hey! Hope you don't mind me opening an issue about this. I'm one of the maintainers of Filament.

Today, we're launching a new [Plugins](https://filamentphp.com/plugins) list on filamentphp.com, and I'd love to see this plugin alongside our others. Hopefully it will serve as great advertising for your work, to our community.

If you'd like to submit your plugin, create an account [here](https://filamentphp.com/admin/register). If you're not interested, feel free to close this issue, no hard feelings :)

Dan

**Comment by stephenjude** [comment]
Hi, @danharrin

This is awesome, and I have submitted the plugin for review. 

Let me know when it's approved so I can close this issue.

**Comment by danharrin** [comment]
All done! Thank you very much
